### PR TITLE
Ensure we create the config directory before we write to it

### LINKED ISSUE #596: `pscale auth login` fails on a new machine
I'm setting up on my laptop. I installed `pscale` via `brew`. Then, running `pscale auth login` does the oauth dance with the browser fine, but then fails with the error: 

```
~ pscale auth login

Confirmation Code:<code>

If something goes wrong, copy and paste this URL into your browser: https://auth.planetscale.com/oauth/device?user_code=<coid>

Successfully logged in.
Error: open /Users/threepointone/.config/planetscale/pscale.yml: no such file or directory
```

This happened multiple times. I fixed it by creating the `/Users/threepointone/.config/planetscale` folder, so I suspect the bug is that the cli is trying to create the `pscale.yml` file without first checking whether the directory exists.

### PR DESCRIPTION
**Pull request by fooforge**
WIP

Fixes #596

### CODE REVIEW

File: internal/cmd/auth/login.go [hunk 1]
```diff
@@ -99,6 +99,12 @@ func writeDefaultOrganization(ctx context.Context, accessToken, authURL string)
 		return err
 	}
 
+	// If the configuration directory doesn't exist, we create it.
+	err = config.CreateConfigDir()
+	if err != nil {
+		return err
+	}
```
Comment (dbussink) [inline internal/cmd/auth/login.go:106]: What about moving this into `WriteDefault()` instead? Where we do the actual file write?

Comment (fooforge) [reply internal/cmd/auth/login.go]: Good call, thanks!

**Review by dbussink — APPROVED** [review]
